services:
  - type: web
    name: back-portfolio
    env: python
    plan: free  
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn Back.wsgi:application"  
    envVars:
      - key: SECRET_KEY
        value: "votre-clé-secrète"  
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"  
    autoDeploy: true
